---
- name: Should execute nvm install tasks
  include_tasks:
    file: install.yml
  when: install|bool

- name: Should execute nvm uninstall tasks
  include_tasks:
    file: uninstall.yml
  when: not install|bool
