---
- name: Uninstall nvm
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - ~/.pm2
    - ~/.npm
    - ~/.nvm

- name: Delete lines to load nvm
  blockinfile:
    path: '{{ nvm_profile }}'
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    state: absent
