- name: Servers setup
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/servers.yml
  tasks:
    - name: Generate server list for hosts file
      set_fact:
        hosts_content: "{{ lookup('template', '../templates/hosts.j2') }}"

    - name: Add servers on /etc/hosts file
      blockinfile:
        dest: /etc/hosts
        content: '{{ hosts_content }}'
        state: present
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Generate server list for ssh config file
      set_fact:
        config_content: "{{ lookup('template', '../templates/ssh_config.j2') }}"

    - name: Create a ssh config file if it does not exist
      file:
        path: ~/.ssh/config
        state: touch
        access_time: preserve
        modification_time: preserve
        mode: 0644

    - name: Add servers on ~/.ssh/config file
      blockinfile:
        dest: ~/.ssh/config
        content: '{{ config_content }}'
        state: present
        backup: yes
